'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const {days,photos,alternatives}=TRIP;
const map=(a,b,mode)=>'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(a)+'&destination='+encodeURIComponent(b)+'&travelmode='+mode;
const searchMap=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const link=(href,label)=>'<a class="map-button" target="_blank" rel="noopener" href="'+esc(href)+'">'+esc(label)+' ↗</a>';
let selected='day-1',lastFocus=null;
const tasks=['确认国际航班、65分钟香港转机及行李直挂','确认酒店早餐时段、早出打包与退房安排','9/27观鲸：07:40前到Campbell’s Cove Pontoon','9/29用NextThere核对08:13、11:00、15:01、16:55班次，并确认The Hill Bar营业','9/30复核08:17、10:15、11:50、14:02、15:16、16:40公交与渡轮','确认10/2及10/3集合点、火车票时刻和实际停靠景点','落实海景晚餐与Steer Dining Room订位','10/4按当地夏令时；10/5目标12:15抵达机场'];
const luggageGroups=[
 ['证件与支付',['护照（与签证绑定护照一致）','澳大利亚签证批准信／电子版离线存档','身份证','证件电子版：手机离线＋云端备份','银行卡／信用卡＋少量澳元现金','机票、酒店、火车与活动订单截图','旅行保险保单＋紧急联系电话','黑色签字笔（填写入境旅客卡）','按需｜驾照＋认可翻译件（本次不自驾可不带）']],
 ['衣物与穿搭',['日常衣服','拍照穿搭','防风防水外套＋可叠穿薄毛衣','防晒衣','泳衣','内衣／胸贴','睡衣','一次性内裤＋袜子','舒适防滑运动鞋','拖鞋','遮阳帽＋墨镜','丝巾／围巾／帽子','饰品、首饰、手表与腰带']],
 ['洗漱用品 · 小样',['牙刷、牙膏与牙线','洗发水、护发素与护发精油','沐浴露与身体乳','止汗露与剃须刀','一次性马桶垫','按需｜一次性四件套','一次性毛巾／浴巾','干发帽','一次性洗脸巾','按需｜折叠衣架','按需｜花洒喷头','搓澡巾']],
 ['护肤修护',['卸妆产品＋化妆棉','洗面奶','爽肤水','乳液','精华','面霜','眼霜','面部高倍防晒','身体防晒','补水面膜／眼膜','痘痘贴','润唇膏','护手霜','修眉刀']],
 ['彩妆与工具',['化妆包','底妆＋遮瑕','眉笔＋眼影＋眼线＋睫毛膏','腮红＋口红＋定妆产品','化妆刷／粉扑＋睫毛夹','按需｜隐形眼镜、护理液与备用眼镜']],
 ['电子数码',['手机','耳机','Pocket 3＋存储卡＋保护盒','各种充电器与数据线','充电宝：≤100Wh、最多2个、仅随身携带','澳标Type I转换插头','小型排插','自拍杆／三脚支架','电话卡／eSIM＋取卡针','按需｜电脑及充电器','行李牌＋AirTag／定位器']],
 ['常备药品',['肠胃药','感冒药＋退烧药','痛经／止痛药','晕车／晕船药','过敏药','创可贴＋消毒棉片／碘伏棉棒','驱蚊液＋止痒膏','口腔溃疡贴','个人专属常备药','处方药原包装＋处方／英文医生说明','电子体温计']],
 ['卫生与收纳',['耳塞＋眼罩','干湿分离收纳袋','护肤品分装瓶','卫生巾／护垫','镜子＋梳子','折叠雨伞','U型枕','家钥匙','酒精湿巾','便携纸巾','口罩＋发圈＋发夹','密封袋／备用塑料袋','脏衣袋','折叠购物袋','保温杯／水杯','行李秤','长途飞行压缩袜']],
 ['入境、航空与退税',['入境前清理肉蛋奶、水果、种子等食品；不确定就申报','液体单瓶≤100ml，放透明袋随身过安检','充电宝不托运；国泰航班不放头顶行李架、不在机上使用','重要证件、药品、相机与贵重物品放随身行李','TRS商品、吊牌与同店满A$300发票','TRS商品随身携带／穿着，提前填写TRS App']]
];
let checked={};try{checked=JSON.parse(localStorage.getItem('au-mobile-checks-v2')||'{}');}catch{}
function imageCard(id,extra='') {const p=photos[id];return '<div class="event-card"><button class="photo-button" data-photo="'+id+'" aria-label="放大'+esc(p.cn)+'"><img src="'+p.src+'" alt="'+esc(p.cn)+'" width="'+p.width+'" height="'+p.height+'" loading="lazy" decoding="async"><span>查看大图</span></button><div class="event-copy"><h3>'+esc(p.cn)+'</h3><span class="english">'+esc(p.en)+'</span>'+extra+'</div></div>';}
function event(r){
 const time='<time class="time">'+esc(r.time)+'</time>';
 if(r.ids.length)return '<article class="event stop">'+time+imageCard(r.ids[0],'<p>'+esc(r.note)+'</p>')+'</article>';
 if(r.kind==='move')return '<article class="event move">'+time+'<details class="event-card"><summary>'+esc(r.title)+'</summary><div class="event-copy"><p>'+esc(r.note)+'</p>'+(r.origin?link(map(r.origin,r.dest,r.mode),r.mode==='transit'?'查看公交／火车班次':r.mode==='walking'?'打开步行导航':'查看行车路线'):'<span class="note">使用叫车软件填写实际地址</span>')+'</div></details></article>';
 if(r.kind==='meal')return '<article class="event meal">'+time+'<div class="event-card event-copy"><h3>'+esc(r.title)+'</h3><p class="'+(r.food?'':'unplanned')+'">'+esc(r.food||'【暂未安排】')+'</p>'+(r.note?'<p class="note">'+esc(r.note)+'</p>':'')+'</div></article>';
 return '<article class="event plain">'+time+'<div class="event-card event-copy"><h3>'+esc(r.title)+'</h3>'+(r.note?'<p>'+esc(r.note)+'</p>':'')+'</div></article>';
}
function dayView(d){
 const idx=days.indexOf(d),stops=d.rows.filter(r=>r.ids.length).length,mealCount=d.rows.filter(r=>r.kind==='meal'&&!r.food).length;
 const overnight=idx===0?'夜宿机上':idx<6?'Little National · 悉尼':idx===10?'退房返程 · 10/6到家':'Holiday Inn Express · 墨尔本';
 return '<div class="day-layout"><aside class="day-overview"><div class="day-hero"><img src="'+photos[d.cover].src+'" alt="'+esc(photos[d.cover].cn)+'" fetchpriority="high"><div class="hero-copy"><span class="eyebrow">'+esc(d.date)+' / '+esc(d.city)+'</span><h1>'+esc(d.title)+'</h1><p>2026 · '+(idx===0?'出发日':idx===10?'返程日':'第 '+idx+' 天')+'</p></div></div><div class="day-meta"><div><small>今天看什么</small><strong>'+stops+' 个图文停留点</strong></div><div><small>餐食待定</small><strong>'+mealCount+' 餐 · 已留时间</strong></div></div><a class="stay-link" href="#stay-food"><span>'+esc(overnight)+'</span><span>↗</span></a><details class="assessment"><summary>时间评估与当天提醒</summary><p>'+esc(d.assessment)+'</p></details><p class="note">当地时间 · 交通为规划估算<br>点击交通卡展开路线，出发前核对班次。</p></aside><section aria-label="当天时间线"><div class="track-head"><h2>按时间出发</h2><span>景点 / 交通 / 三餐</span></div><div class="timeline">'+d.rows.map(event).join('')+'</div>'+(d.optional.length?'<details class="optional"><summary>可选支线／团方候选 · 不与主线叠加</summary><div class="timeline">'+d.optional.map(event).join('')+'</div></details>':'')+'<div class="day-pager">'+(idx?'<a href="#'+days[idx-1].id+'">← '+days[idx-1].date.split(' ')[0]+' 上一天</a>':'')+(idx<days.length-1?'<a href="#'+days[idx+1].id+'">下一天 '+days[idx+1].date.split(' ')[0]+' →</a>':'<a href="#info">查看返程资料 →</a>')+'</div></section></div>';
}
function hotelsContent(){return '<div class="hotel-grid"><article class="hotel-card"><span class="city-label">SYDNEY / 悉尼</span><h2>悉尼小国民酒店</h2><h3>Little National Hotel Sydney</h3><dl><dt>入住</dt><dd>9/26 → 10/1 · 5晚 · 已订</dd><dt>地址</dt><dd>26 Clarence St, Sydney</dd><dt>早餐</dt><dd>是否包含待确认</dd><dt>车站</dt><dd>Wynyard步行约2–4分钟</dd><dt>机场</dt><dd>T8 Airport Link，含候车步行预留约60分钟</dd><dt>费用</dt><dd>¥12,685.74 / 4人全程</dd></dl>'+link(searchMap('Little National Hotel Sydney 26 Clarence Street'),'酒店地图')+'</article><article class="hotel-card"><span class="city-label">MELBOURNE / 墨尔本</span><h2>小柯林斯街智选假日</h2><h3>Holiday Inn Express Little Collins</h3><dl><dt>入住</dt><dd>10/1 → 10/5 · 4晚 · 已订</dd><dt>地址</dt><dd>589–599 Little Collins St, Melbourne</dd><dt>早餐</dt><dd>10/2–10/5含早，供餐时段／打包待确认</dd><dt>车站</dt><dd>Southern Cross步行约5–7分钟</dd><dt>机场</dt><dd>SkyBus机场巴士，含候车步行预留60–75分钟</dd><dt>费用</dt><dd>¥6,899.56 / 4人全程</dd></dl>'+link(searchMap('Holiday Inn Express Melbourne Little Collins'),'酒店地图')+'</article></div><article class="info-card"><h2>两个退房早晨</h2><p><b>10/1 06:15</b> 悉尼离店 → T2 → 09:00 VA824。早餐提前准备。</p><p><b>10/5 11:15</b> 墨尔本离店前往机场，目标12:15抵达T2，15:25 CX104起飞。</p></article>';}
function foodContent(){const meals=days.flatMap(d=>d.rows.filter(r=>r.kind==='meal').map(r=>({day:d,time:r.time,title:r.title,food:r.food,note:r.note})));return '<div class="meal-list">'+meals.map(m=>'<a class="meal-row" href="#'+m.day.id+'"><div><small>'+esc(m.day.date)+' · '+esc(m.time)+'</small><b>'+esc(m.title)+'</b></div><span class="'+(m.food?'':'unplanned')+'">'+esc(m.food||'【暂未安排】')+'</span>'+(m.note?'<em>'+esc(m.note)+'</em>':'')+'</a>').join('')+'</div>';}
function segmented(title,intro,tabs){return '<h1 class="section-title">'+title+'</h1><p class="section-intro">'+intro+'</p><div class="segment-shell"><div class="segmented" role="tablist">'+tabs.map((t,i)=>'<button role="tab" data-segment="'+t.id+'" aria-selected="'+(i?'false':'true')+'">'+t.label+'</button>').join('')+'</div>'+tabs.map((t,i)=>'<section class="segment-panel" data-segment-panel="'+t.id+'" '+(i?'hidden':'')+'>'+t.content+'</section>').join('')+'</div>';}
function stayFoodView(){return segmented('吃住安排','酒店信息与每日用餐集中查看；点击餐次可回到当天时间线。',[{id:'hotels',label:'酒店',content:hotelsContent()},{id:'food',label:'美食',content:foodContent()}]);}
function alternativesView(){return '<h1 class="section-title">备选景点</h1><p class="section-intro">这些景点已移出主行程，照片保留在这里。临时替换时需重新核对交通与时间。</p><div class="alternatives-grid">'+alternatives.map(id=>imageCard(id,'<p>'+link(searchMap(photos[id].en+(id==='arcade'?' Melbourne':' Sydney')),'查看位置')+'</p>')).join('')+'</div>';}
function shoppingContent(){return '<div class="shop-grid"><article class="info-card"><small>首选 · 9/30 10:45–11:45</small><h2>Arc’teryx · Westfield Bondi Junction</h2><p>安排在Coogee与Bondi Beach之间，购物1小时。同行人可在商场休息。</p>'+link(searchMap("Arc\'teryx Westfield Bondi Junction"),'商场导航')+'<p class="note">同一商店单张发票尽量满A$300，保留商品、吊牌和发票。</p></article><article class="info-card"><small>Plan B · 9/28 15:55–17:30</small><h2>Arc’teryx · The Galeries</h2><p>500 George St，距悉尼酒店步行约5–8分钟；仅在9/30需要释放时间时启用。</p>'+link(searchMap("Arc\'teryx The Galeries Sydney"),'门店导航')+'</article><article class="info-card"><h2>TRS退税</h2><p>10/5只在墨尔本机场T2国际出发办理。商品随身携带或穿着，勿托运；提前填写TRS App并备好发票。</p></article></div>';}
function photoContent(){const groups=days.map(d=>({d,ids:[...new Set(d.rows.flatMap(r=>r.ids))]})).filter(g=>g.ids.length);return '<div class="photo-index">'+groups.map(g=>'<section class="photo-day"><a href="#'+g.d.id+'"><small>'+esc(g.d.date)+'</small><b>'+esc(g.d.title)+'</b></a><div>'+g.ids.map(id=>imageCard(id)).join('')+'</div></section>').join('')+'</div><a class="wide-link" href="#alternatives">查看备选景点与照片 →</a>';}
function shopPhotoView(){return segmented('逛拍清单','购物与拍照点分开查看，照片仍可点击放大。',[{id:'shopping',label:'购物',content:shoppingContent()},{id:'photos',label:'拍照',content:photoContent()}]);}
function luggageView(){let index=0,total=luggageGroups.reduce((sum,g)=>sum+g[1].length,0);const groups=luggageGroups.map(g=>'<section class="luggage-group"><h2>'+esc(g[0])+'<small>'+g[1].length+'项</small></h2>'+g[1].map(item=>{const key='luggage-'+index++;return '<label><input type="checkbox" data-check="'+key+'" '+(checked[key]?'checked':'')+'><span>'+esc(item)+'</span></label>';}).join('')+'</section>').join('');return '<h1 class="section-title">行李清单</h1><p class="section-intro">共'+total+'项 · “按需”项目根据个人情况选择；勾选状态只保存在当前手机浏览器。</p><div class="luggage-grid">'+groups+'</div><article class="info-card"><h2>本次航班特别提醒</h2><p>国泰现行规则：每人最多携带2个充电宝，仅限随身行李；不得放头顶行李架，也不能在机上使用或充电。</p><p>'+link('https://www.cathaypacific.com/cx/zh_CN/baggage/controlled-and-banned-items/lithium-batteries.html','国泰电池规则')+' '+link('https://immi.homeaffairs.gov.au/entering-and-leaving-australia/entering-australia/crossing-the-border','澳洲入境说明')+'</p></article><p id="save-note" class="note">换手机或清除浏览器数据后，需要重新勾选。</p>';}
function moreInfoView(){return '<h1 class="section-title">更多资料</h1><p class="section-intro">9/25出发 · 10/6凌晨到家 · 所有航班为所在地当地时间</p><article class="info-card"><h2>航班与转机</h2>'+[
 ['9/25 · CX989','22:20 广州T3 → 23:40 香港','18:15从家中打车出发，目标19:15–19:45到机场。'],['9/26 · CX181','00:45 香港T1 → 11:45 悉尼','香港仅65分钟转机，机场内直达下一登机口。'],['10/1 · VA824','09:00 悉尼T2 → 10:35 墨尔本T3','06:15退房前往机场，机上无餐食。'],['10/5 · CX104','15:25 墨尔本T2 → 21:45 香港','目标12:15到机场，香港转机3小时30分钟。'],['10/6 · CX950','01:15 香港T1 → 02:20 广州','入境取行李后打车返家，预计04:20左右到家。']].map(f=>'<div class="flight"><strong>'+f[0]+'</strong>'+f[1]+'<br><span>'+f[2]+'</span></div>').join('')+'</article><article class="info-card"><h2>费用速查 / 4人</h2><div class="money"><div><small>人民币已确认</small><b>¥70,046.02</b><small>人均 ¥17,511.51</small></div><div><small>观鲸单独结算</small><b>A$604.94</b><small>澳元，不与人民币直接相加</small></div><div><small>餐饮预算估计</small><b>≈ A$2,760</b><small>人均 ≈ A$690，非已付款</small></div><div><small>酒店总住宿</small><b>9晚</b><small>悉尼5晚＋墨尔本4晚</small></div></div></article><article class="info-card"><h2>时间与交通说明</h2><ul><li>路线耗时为规划估算，非实时班次；点击导航后设置实际出行日期。</li><li>9/29与9/30需在前一晚复核公交、列车与渡轮时刻。</li><li>10/2大洋路、10/3蒸汽火车企鹅团以团方最终通知为准。</li><li>10/4进入夏令时，悉尼／墨尔本比中国快3小时；此前快2小时。</li></ul><p>'+link('https://transportnsw.info/trip','悉尼官方交通')+' '+link('https://www.ptv.vic.gov.au/journey','墨尔本官方交通')+'</p></article><a class="wide-link" href="#alternatives">查看备选景点 →</a><p class="note">照片版权归原作者或来源方，点击照片可查看来源。家庭详细地址及订单编号未包含在此公开页面。</p>';}
function infoView(){return '<h1 class="section-title">出行资料</h1><p class="section-intro">9/25出发 · 10/6凌晨到家 · 所有航班为所在地当地时间</p><article class="info-card"><h2>航班与转机</h2>'+[
 ['9/25 · CX989','22:20 广州T3 → 23:40 香港','18:15从家中打车出发，目标19:15–19:45到机场。'],['9/26 · CX181','00:45 香港T1 → 11:45 悉尼','香港仅65分钟转机，机场内直达下一登机口。'],['10/1 · VA824','09:00 悉尼T2 → 10:35 墨尔本T3','06:15退房前往机场，机上无餐食。'],['10/5 · CX104','15:25 墨尔本T2 → 21:45 香港','目标12:15到机场，香港转机3小时30分钟。'],['10/6 · CX950','01:15 香港T1 → 02:20 广州','入境取行李后打车返家，预计04:20左右到家。']].map(f=>'<div class="flight"><strong>'+f[0]+'</strong>'+f[1]+'<br><span>'+f[2]+'</span></div>').join('')+'</article><article class="info-card"><h2>费用速查 / 4人</h2><div class="money"><div><small>人民币已确认</small><b>¥70,046.02</b><small>人均 ¥17,511.51</small></div><div><small>观鲸单独结算</small><b>A$604.94</b><small>澳元，不与人民币直接相加</small></div><div><small>餐饮预算估计</small><b>≈ A$2,760</b><small>人均 ≈ A$690，非已付款</small></div><div><small>酒店总住宿</small><b>9晚</b><small>悉尼5晚＋墨尔本4晚</small></div></div></article><article class="info-card"><h2>用餐安排</h2><p><b>9/27午餐</b> Pancakes on the Rocks<br><b>9/27晚餐</b> Cafe Sydney / Opera Bar二选一，待订<br><b>9/28午餐</b> 新悉尼鱼市场海鲜<br><b>10/4午餐</b> 南墨尔本市场Dim Sims＋生蚝<br><b>10/4晚餐</b> Steer Dining Room和牛，South Yarra，待订</p><p>其他未定餐食在时间线上以<span class="unplanned">【暂未安排】</span>标识。沃森湾Doyles为可选，Garfish仅随曼利备选路线考虑。</p></article><article class="info-card checklist"><h2>出发前待办</h2>'+tasks.map((t,i)=>'<label><input type="checkbox" data-check="'+i+'" '+(checked[i]?'checked':'')+'><span>'+esc(t)+'</span></label>').join('')+'<p id="save-note" class="note">勾选仅保存在当前设备浏览器。</p></article><article class="info-card"><h2>时间与交通说明</h2><ul><li>路线耗时为规划估算，非实时Google Maps班次；点击导航后设置实际出行日期。</li><li>10/2大洋路、10/3蒸汽火车企鹅团时刻为示意，集合点、火车班次和部分停靠点待团方通知。</li><li>10/4进入夏令时，悉尼／墨尔本比中国快3小时；此前快2小时。</li><li>资料核对日期2026/9/14。航班及酒店以订单与最新通知为准。</li></ul><p>'+link('https://transportnsw.info/trip','悉尼官方交通')+' '+link('https://www.ptv.vic.gov.au/journey','墨尔本官方交通')+'</p><p>'+link('https://www.sydneyfishmarket.com.au/plan-your-visit/','新鱼市场')+' '+link('https://www.slv.vic.gov.au/visit/opening-hours','州立图书馆')+'</p><p>'+link('https://www.unimelb.edu.au/old-quad/visit','墨尔本大学')+' '+link('https://www.skybus.com.au/melbourne-city-express/','机场巴士')+'</p></article><p class="note">照片版权归原作者或来源方，点击照片可查看来源。照片仅作景点识别，实际现场状态可能不同。家庭详细地址及订单编号未包含在此公开页面。</p>';}
function render(){
 const hash=decodeURIComponent(location.hash.slice(1)),d=days.find(d=>d.id===hash);let view;
 if(['stay-food','shop-photo','luggage','info','hotels','alternatives'].includes(hash)){view=hash==='hotels'?'stay-food':hash==='alternatives'?'shop-photo':hash;$('#main').innerHTML=hash==='stay-food'||hash==='hotels'?stayFoodView():hash==='shop-photo'?shopPhotoView():hash==='luggage'?luggageView():hash==='alternatives'?alternativesView():moreInfoView();}
 else{view='trip';selected=d?.id||selected;$('#main').innerHTML=dayView(days.find(d=>d.id===selected));}
 $('#datebar').hidden=view!=='trip';document.querySelectorAll('[data-view]').forEach(a=>{a.toggleAttribute('aria-current',a.dataset.view===view);if(a.dataset.view===view)a.setAttribute('aria-current','page');});
 document.querySelectorAll('.date-chip').forEach(a=>{if(a.hash==='#'+selected)a.setAttribute('aria-current','date');else a.removeAttribute('aria-current');});
 document.querySelector('[data-view="trip"]').href='#'+selected;
 document.title=(view==='trip'?days.find(d=>d.id===selected).date+' '+days.find(d=>d.id===selected).title:({'stay-food':'吃住安排','shop-photo':'逛拍清单',luggage:'行李与待办',info:'更多资料'})[view])+'｜澳大利亚随行手册';
 window.scrollTo({top:0,behavior:'instant'});if(view==='trip'){const chip=document.querySelector('.date-chip[aria-current]'),rail=$('#dates');rail.scrollLeft=chip.offsetLeft-rail.offsetLeft-rail.clientWidth/2+chip.clientWidth/2;}
}
function directory(q=''){const term=q.trim().toLowerCase();const results=days.filter(d=>(JSON.stringify(d)+' '+[...d.rows,...d.optional].flatMap(r=>r.ids).map(id=>photos[id].cn+' '+photos[id].en).join(' ')).toLowerCase().includes(term));$('#directory-results').innerHTML=results.map(d=>'<a class="directory-item" href="#'+d.id+'"><small>'+esc(d.date)+' / '+esc(d.city)+'</small><b>'+esc(d.title)+'</b><p>'+d.rows.flatMap(r=>r.ids).map(id=>esc(photos[id].cn)).join(' · ')+'</p></a>').join('')+(results.length?'':'<p class="empty">没有找到匹配的行程，试试其他名称。</p>');}
$('#dates').innerHTML=days.map(d=>'<a class="date-chip" href="#'+d.id+'"><b>'+d.date.split(' ')[0]+'</b><span>'+d.date.split(' ')[1]+'</span></a>').join('');
$('#directory-button').onclick=()=>{lastFocus=document.activeElement;directory();$('#search').value='';$('#directory').showModal();};$('#search').addEventListener('input',e=>directory(e.target.value));
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)$('#'+close.dataset.close).close();const item=e.target.closest('.directory-item');if(item){$('#directory').close();if(location.hash===item.hash)render();}
 const segment=e.target.closest('[data-segment]');if(segment){const shell=segment.closest('.segment-shell');shell.querySelectorAll('[data-segment]').forEach(button=>button.setAttribute('aria-selected',String(button===segment)));shell.querySelectorAll('[data-segment-panel]').forEach(panel=>panel.hidden=panel.dataset.segmentPanel!==segment.dataset.segment);}
 const photo=e.target.closest('[data-photo]');if(photo){const p=photos[photo.dataset.photo];lastFocus=photo;$('#photo-title').textContent=p.cn;$('#photo-large').src=p.src;$('#photo-large').alt=p.cn;$('#photo-english').textContent=p.en;$('#photo-source').href=p.source;$('#photo-source').textContent='图片来源 · '+p.credit+' ↗';$('#photo-dialog').showModal();}});
document.addEventListener('change',e=>{if(e.target.matches('[data-check]')){checked[e.target.dataset.check]=e.target.checked;try{localStorage.setItem('au-mobile-checks-v2',JSON.stringify(checked));}catch{$('#save-note').textContent='当前浏览器无法保存，勾选仅本次有效。';}}});
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus();});});
window.addEventListener('hashchange',render);render();
