'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const {days,photos,alternatives}=TRIP;
Object.assign(photos,{
 'hotel-sydney-entrance':{cn:'悉尼小国民酒店正门',en:'Little National Hotel Sydney',source:'https://littlenationalhotel.com.au/sydney/',credit:'酒店官网',src:'assets/little-national-entrance.webp',width:625,height:1000},
 'hotel-sydney-room':{cn:'悉尼小国民酒店大床房',en:'Little National Room',source:'https://littlenationalhotel.com.au/sydney/rooms/ln-rooms/?lang=en',credit:'酒店官网',src:'assets/little-national-room.webp',width:1000,height:750},
 'hotel-melbourne-entrance':{cn:'墨尔本智选假日酒店正门',en:'Holiday Inn Express Melbourne Little Collins',source:'https://www.ihg.com/holidayinnexpress/hotels/us/en/melbourne/mellc/hoteldetail',credit:'IHG酒店官网',src:'assets/holiday-inn-entrance.webp',width:1000,height:929},
 'hotel-melbourne-room':{cn:'墨尔本智选假日大床房',en:'Standard Room',source:'https://www.ihg.com/holidayinnexpress/hotels/us/en/melbourne/mellc/hoteldetail',credit:'IHG酒店官网',src:'assets/holiday-inn-room.webp',width:1000,height:667}
});
const map=(a,b,mode)=>'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(a)+'&destination='+encodeURIComponent(b)+'&travelmode='+mode;
const searchMap=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const link=(href,label)=>'<a class="map-button" target="_blank" rel="noopener" href="'+esc(href)+'">'+esc(label)+' ↗</a>';
let selected='day-1',lastFocus=null;
const tasks=['确认国际航班、65分钟香港转机及行李直挂','确认酒店早餐时段、早出打包与退房安排','9/27观鲸：07:40前到Campbell’s Cove Pontoon','9/29用NextThere核对08:13、11:00、15:01、16:55班次，并确认The Hill Bar营业','9/30复核08:17、10:15、11:50、14:02、15:16、16:40公交与渡轮','确认10/2及10/3集合点、火车票时刻和实际停靠景点','落实海景晚餐与Steer Dining Room订位','10/4按当地夏令时；10/5目标12:15抵达机场'];
const luggageGroups=[
 ['证件与支付',['护照（与签证绑定护照一致）','澳大利亚签证批准信／电子版离线存档','身份证','证件电子版：手机离线＋云端备份','银行卡／信用卡＋少量澳元现金','机票、酒店、火车与活动订单截图','旅行保险保单＋紧急联系电话','黑色签字笔（填写入境旅客卡）','按需｜驾照＋认可翻译件（本次不自驾可不带）']],
 ['衣物与穿搭',['日常衣服','拍照穿搭','防风防水外套＋可叠穿薄毛衣','防晒衣','泳衣','内衣／胸贴','睡衣','一次性内裤＋袜子','舒适防滑运动鞋','拖鞋','遮阳帽＋墨镜','丝巾／围巾／帽子','饰品、首饰、手表与腰带']],
 ['洗漱用品 · 小样',['牙刷、牙膏与牙线','洗发水、护发素与护发精油','沐浴露与身体乳','止汗露与剃须刀','一次性马桶垫','按需｜一次性四件套','一次性毛巾／浴巾','干发帽','一次性洗脸巾','按需｜折叠衣架','按需｜花洒喷头','搓澡巾']],
 ['护肤修护',['卸妆产品＋化妆棉','洗面奶','爽肤水','乳液','精华','面霜','眼霜','面部高倍防晒','身体防晒','补水面膜／眼膜','痘痘贴','润唇膏','护手霜','修眉刀']],
 ['彩妆与工具',['化妆包','底妆＋遮瑕','眉笔＋眼影＋眼线＋睫毛膏','腮红＋口红＋定妆产品','化妆刷／粉扑＋睫毛夹','按需｜隐形眼镜、护理液与备用眼镜']],
 ['电子数码',['手机','耳机','Pocket 3＋存储卡＋保护盒','各种充电器与数据线','充电宝：≤100Wh、最多2个、仅随身携带','澳标Type I转换插头','小型排插','自拍杆／三脚支架','电话卡／eSIM＋取卡针','按需｜电脑及充电器','行李牌＋AirTag／定位器']],
 ['常备药品',['肠胃药','感冒药＋退烧药','痛经／止痛药','晕车／晕船药','过敏药','创可贴＋消毒棉片／碘伏棉棒','驱蚊液＋止痒膏','口腔溃疡贴','个人专属常备药','处方药原包装＋处方／英文医生说明','电子体温计']],
 ['卫生与收纳',['耳塞＋眼罩','干湿分离收纳袋','护肤品分装瓶','卫生巾／护垫','镜子＋梳子','折叠雨伞','U型枕','家钥匙','酒精湿巾','便携纸巾','口罩＋发圈＋发夹','密封袋／备用塑料袋','脏衣袋','折叠购物袋','保温杯／水杯','行李秤','长途飞行压缩袜']],
 ['入境、航空与退税',['入境前清理肉蛋奶、水果、种子等食品；不确定就申报','液体单瓶≤100ml，放透明袋随身过安检','充电宝不托运；国泰航班不放头顶行李架、不在机上使用','重要证件、药品、相机与贵重物品放随身行李','TRS商品、吊牌与同店满A$300发票','TRS商品随身携带／穿着，提前填写TRS App']]
];
let checked={};try{checked=JSON.parse(localStorage.getItem('au-mobile-checks-v2')||'{}');}catch{}
const icon=(name,cls='')=>{const paths={pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',train:'<rect x="5" y="3" width="14" height="16" rx="3"/><path d="M8 21l2-2M16 19l2 2M8 8h8M8 14h.01M16 14h.01"/>',walk:'<circle cx="13" cy="4" r="2"/><path d="m10 22 1-7-3-3 2-5 4 3 3 1M15 22l-2-6 4-2"/>',car:'<path d="m5 17-2-2 2-6h14l2 6-2 2H5Z"/><path d="m7 9 2-4h6l2 4M6 17v3M18 17v3M7 14h.01M17 14h.01"/>',plane:'<path d="M22 2 9 15M22 2l-6 20-4-9-9-4 19-7Z"/>',fork:'<path d="M3 2v7a3 3 0 0 0 3 3V2M6 2v20M13 2v8a4 4 0 0 0 4 4h2M19 2v20"/>',shop:'<path d="M4 7h16l-1 14H5L4 7Z"/><path d="M8 9V5a4 4 0 0 1 8 0v4"/>',building:'<path d="M4 22V4l8-2 8 2v18M9 8h.01M15 8h.01M9 12h.01M15 12h.01M9 16h.01M15 16h.01M10 22v-3h4v3"/>',chevron:'<path d="m9 18 6-6-6-6"/>',zoom:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'};return '<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true">'+(paths[name]||paths.pin)+'</svg>';};
function timeMeta(value){const matches=String(value).match(/\d{1,2}:\d{2}/g)||[];if(!matches.length)return {primary:String(value).split(/[–—]/)[0],period:'',until:''};const hour=Number(matches[0].split(':')[0]),period=hour<6?'凌晨':hour<12?'上午':hour<14?'中午':hour<18?'下午':'晚上';return {primary:matches[0],period,until:matches[1]?'至 '+matches[1]:''};}
function placeType(r){const text=(r.title+' '+r.note).toLowerCase();if(/机场|airport|cx\d|va\d|航班|登机|安检|候机/.test(text))return ['景点','plane'];if(/购物|手信|minimeeq|mini meeq|paddy|arc.?teryx|westfield|pitt street|qvb/.test(text))return ['景点','shop'];if(/酒店|入住|退房|行李/.test(text))return ['景点','building'];return ['景点','pin'];}
function travelIcon(mode){return mode==='walking'?'walk':mode==='driving'?'car':mode==='transit'?'train':'train';}
function railTime(r){const t=timeMeta(r.time);return '<div class="time-block"><time class="time">'+esc(t.primary)+'</time><span>'+esc(t.period)+'</span>'+(t.until?'<small>'+esc(t.until)+'</small>':'')+'</div>';}
function imageCard(id,extra='') {const p=photos[id];if(!p)return '';return '<div class="event-card"><button class="photo-button" data-photo="'+id+'" aria-label="放大'+esc(p.cn)+'"><img src="'+p.src+'" alt="'+esc(p.cn)+'" width="'+p.width+'" height="'+p.height+'" loading="lazy" decoding="async"><span>查看大图</span></button><div class="event-copy"><h3>'+esc(p.cn)+'</h3><span class="english">'+esc(p.en)+'</span>'+extra+'</div></div>';}
function event(r){
 const time=railTime(r);
 if(r.kind==='move')return '<article class="event move">'+time+'<details class="route-strip"><summary><span class="route-symbol">'+icon(travelIcon(r.mode))+'</span><span class="route-main"><span class="type-badge">交通</span><b>'+esc(r.title)+'</b>'+(r.origin&&r.dest?'<small>'+esc(r.origin)+' → '+esc(r.dest)+'</small>':'')+'</span><span class="route-chevron">'+icon('chevron')+'</span></summary><div class="route-detail"><p>'+esc(r.note)+'</p>'+(r.origin?link(map(r.origin,r.dest,r.mode),r.mode==='transit'?'查看公共交通':r.mode==='walking'?'打开步行导航':'查看行车路线'):'<span class="note">使用叫车软件填写实际地址</span>')+'</div></details></article>';
 if(r.kind==='meal'){const mealText=(r.food||'')+' '+r.note,mealPhoto=/鱼市场|龙虾|生蚝|海鲜/.test(mealText)?'fish':/南墨尔本市场|dim sim/i.test(mealText)?'market':'';return '<article class="event meal">'+time+'<div class="event-card meal-card">'+(mealPhoto?'<button class="photo-button" data-photo="'+mealPhoto+'" aria-label="查看用餐地点照片"><img src="'+photos[mealPhoto].src+'" alt="'+esc(photos[mealPhoto].cn)+'" loading="lazy"></button>':'<div class="meal-visual">'+icon('fork')+'</div>')+'<div class="event-copy"><div class="card-top"><span class="type-badge">美食</span></div><h3>'+esc(r.title)+'</h3><span class="english '+(r.food?'':'unplanned')+'">'+esc(r.food||'【暂未安排】')+'</span>'+(r.note?'<p>'+esc(r.note)+'</p>':'')+'</div></div></article>';}
 const [type,typeIcon]=placeType(r),id=r.ids[0],p=id?photos[id]:null,title=p?p.cn:r.title,english=p?p.en:'',note=p?r.note:r.note;
 return '<article class="event stop">'+time+'<div class="event-card place-card">'+(p?'<button class="photo-button" data-photo="'+id+'" aria-label="放大'+esc(p.cn)+'"><img src="'+p.src+'" alt="'+esc(p.cn)+'" width="'+p.width+'" height="'+p.height+'" loading="lazy" decoding="async"><span>'+icon('zoom')+'</span></button>':'<div class="place-visual">'+icon(typeIcon)+'</div>')+'<div class="event-copy"><div class="card-top"><span class="type-badge">'+type+'</span>'+(p?'<a class="nav-pill" target="_blank" rel="noopener" href="'+esc(searchMap(p.en))+'">'+icon('plane')+'导航</a>':'')+'</div><h3>'+esc(title)+'</h3>'+(english?'<span class="english">'+esc(english)+'</span>':'')+(note?'<p>'+esc(note)+'</p>':'')+'</div></div></article>';
}
function dayView(d){
 const idx=days.indexOf(d);
 return '<div class="day-layout"><section class="day-summary"><img src="'+photos[d.cover].src+'" alt="'+esc(photos[d.cover].cn)+'" fetchpriority="high"><div><span>'+esc(d.date)+' · '+esc(d.city)+'</span><h1>'+esc(d.title)+'</h1><p>2026 · '+(idx===0?'出发日':idx===10?'返程日':'第 '+idx+' 天')+'</p></div></section><section class="day-schedule" aria-label="当天时间线"><div class="track-head"><div><span class="track-kicker">TODAY</span><h2>今日行程</h2></div><p>景点 · 交通 · 美食</p></div><div class="timeline">'+d.rows.map(event).join('')+'</div>'+(d.optional.length?'<details class="optional"><summary>可选支线／团方候选</summary><div class="timeline">'+d.optional.map(event).join('')+'</div></details>':'')+'<div class="day-pager">'+(idx?'<a href="#'+days[idx-1].id+'">← '+days[idx-1].date.split(' ')[0]+'</a>':'')+(idx<days.length-1?'<a href="#'+days[idx+1].id+'">'+days[idx+1].date.split(' ')[0]+' →</a>':'<a href="#profile">返程资料 →</a>')+'</div></section></div>';
}
function hotelsContent(){return '<div class="hotel-grid"><article class="hotel-card"><span class="city-label">SYDNEY / 悉尼</span><h2>悉尼小国民酒店</h2><h3>Little National Hotel Sydney</h3><dl><dt>入住</dt><dd>9/26 → 10/1 · 5晚 · 已订</dd><dt>地址</dt><dd>26 Clarence St, Sydney</dd><dt>早餐</dt><dd>是否包含待确认</dd><dt>车站</dt><dd>Wynyard步行约2–4分钟</dd><dt>机场</dt><dd>T8 Airport Link，含候车步行预留约60分钟</dd><dt>费用</dt><dd>¥12,685.74 / 4人全程</dd></dl>'+link(searchMap('Little National Hotel Sydney 26 Clarence Street'),'酒店地图')+'<div class="hotel-photos">'+imageCard('hotel-sydney-entrance')+imageCard('hotel-sydney-room')+'</div></article><article class="hotel-card"><span class="city-label">MELBOURNE / 墨尔本</span><h2>小柯林斯街智选假日</h2><h3>Holiday Inn Express Little Collins</h3><dl><dt>入住</dt><dd>10/1 → 10/5 · 4晚 · 已订</dd><dt>地址</dt><dd>589–599 Little Collins St, Melbourne</dd><dt>早餐</dt><dd>10/2–10/5含早，供餐时段／打包待确认</dd><dt>车站</dt><dd>Southern Cross步行约5–7分钟</dd><dt>机场</dt><dd>SkyBus机场巴士，含候车步行预留60–75分钟</dd><dt>费用</dt><dd>¥6,899.56 / 4人全程</dd></dl>'+link(searchMap('Holiday Inn Express Melbourne Little Collins'),'酒店地图')+'<div class="hotel-photos">'+imageCard('hotel-melbourne-entrance')+imageCard('hotel-melbourne-room')+'</div></article></div><article class="info-card"><h2>两个退房早晨</h2><p><b>10/1 06:15</b> 悉尼离店 → T2 → 09:00 VA824。早餐提前准备。</p><p><b>10/5 11:15</b> 墨尔本离店前往机场，目标12:15抵达T2，15:25 CX104起飞。</p></article>';}
function foodContent(){const meals=days.flatMap(d=>d.rows.filter(r=>r.kind==='meal').map(r=>({day:d,time:r.time,title:r.title,food:r.food,note:r.note})));return '<div class="meal-list">'+meals.map(m=>'<a class="meal-row" href="#'+m.day.id+'"><div><small>'+esc(m.day.date)+' · '+esc(m.time)+'</small><b>'+esc(m.title)+'</b></div><span class="'+(m.food?'':'unplanned')+'">'+esc(m.food||'【暂未安排】')+'</span>'+(m.note?'<em>'+esc(m.note)+'</em>':'')+'</a>').join('')+'</div>';}
function segmented(title,intro,tabs){return '<h1 class="section-title">'+title+'</h1><p class="section-intro">'+intro+'</p><div class="segment-shell"><div class="segmented" role="tablist">'+tabs.map((t,i)=>'<button role="tab" data-segment="'+t.id+'" aria-selected="'+(i?'false':'true')+'">'+t.label+'</button>').join('')+'</div>'+tabs.map((t,i)=>'<section class="segment-panel" data-segment-panel="'+t.id+'" '+(i?'hidden':'')+'>'+t.content+'</section>').join('')+'</div>';}
function stayFoodView(){return segmented('吃住安排','酒店信息与每日用餐集中查看；点击餐次可回到当天时间线。',[{id:'hotels',label:'酒店',content:hotelsContent()},{id:'food',label:'美食',content:foodContent()}]);}
function alternativesView(){return '<h1 class="section-title">备选景点</h1><p class="section-intro">这些景点已移出主行程，照片保留在这里。临时替换时需重新核对交通与时间。</p><div class="alternatives-grid">'+alternatives.map(id=>imageCard(id,'<p>'+link(searchMap(photos[id].en+(id==='arcade'?' Melbourne':' Sydney')),'查看位置')+'</p>')).join('')+'</div>';}
function shoppingContent(){return '<div class="shop-grid"><article class="info-card"><small>9/28 · 15:30–16:00</small><h2>Mini MeeQ Sydney</h2><p>Westfield Sydney Shop 1027，重点找澳洲限定版Hello Kitty；从QVB步行约4分钟。</p>'+link(searchMap('Mini MeeQ Sydney'),'门店导航')+'</article><article class="info-card"><small>9/30 · 17:35–18:00</small><h2>Paddy’s Markets · 手信</h2><p>Haymarket／Market City内，周三18:00关门。按清单定向购买；渡轮晚点时缩短或取消。</p>'+link(searchMap("Paddy's Markets Haymarket"),'市场导航')+'</article><article class="info-card"><small>9/30 · 10:45–11:45</small><h2>Arc’teryx · Westfield Bondi Junction</h2><p>安排在Coogee与Bondi Beach之间，购物1小时。同行人可在商场休息。</p>'+link(searchMap("Arc\'teryx Westfield Bondi Junction"),'商场导航')+'<p class="note">同一商店单张发票尽量满A$300，保留商品、吊牌和发票。</p></article><article class="info-card"><small>Plan B · 9/28 15:55–17:30</small><h2>Arc’teryx · The Galeries</h2><p>500 George St，距悉尼酒店步行约5–8分钟；仅在9/30需要释放时间时启用。</p>'+link(searchMap("Arc\'teryx The Galeries Sydney"),'门店导航')+'</article><article class="info-card"><h2>TRS退税</h2><p>10/5只在墨尔本机场T2国际出发办理。商品随身携带或穿着，勿托运；提前填写TRS App并备好发票。</p></article></div>';}
function photoContent(){const groups=days.map(d=>({d,ids:[...new Set(d.rows.flatMap(r=>r.ids))]})).filter(g=>g.ids.length);return '<div class="photo-index">'+groups.map(g=>'<section class="photo-day"><a href="#'+g.d.id+'"><small>'+esc(g.d.date)+'</small><b>'+esc(g.d.title)+'</b></a><div>'+g.ids.map(id=>imageCard(id)).join('')+'</div></section>').join('')+'</div><a class="wide-link" href="#alternatives">查看备选景点与照片 →</a>';}
function shopPhotoView(){return segmented('逛拍清单','购物与拍照点分开查看，照片仍可点击放大。',[{id:'shopping',label:'购物',content:shoppingContent()},{id:'photos',label:'拍照',content:photoContent()}]);}
function luggageView(){let index=0,total=luggageGroups.reduce((sum,g)=>sum+g[1].length,0);const groups=luggageGroups.map(g=>'<section class="luggage-group"><h2>'+esc(g[0])+'<small>'+g[1].length+'项</small></h2>'+g[1].map(item=>{const key='luggage-'+index++;return '<label><input type="checkbox" data-check="'+key+'" '+(checked[key]?'checked':'')+'><span>'+esc(item)+'</span></label>';}).join('')+'</section>').join('');return '<h1 class="section-title">行李清单</h1><p class="section-intro">共'+total+'项 · “按需”项目根据个人情况选择；勾选状态只保存在当前手机浏览器。</p><div class="luggage-grid">'+groups+'</div><article class="info-card"><h2>本次航班特别提醒</h2><p>国泰现行规则：每人最多携带2个充电宝，仅限随身行李；不得放头顶行李架，也不能在机上使用或充电。</p><p>'+link('https://www.cathaypacific.com/cx/zh_CN/baggage/controlled-and-banned-items/lithium-batteries.html','国泰电池规则')+' '+link('https://immi.homeaffairs.gov.au/entering-and-leaving-australia/entering-australia/crossing-the-border','澳洲入境说明')+'</p></article><p id="save-note" class="note">换手机或清除浏览器数据后，需要重新勾选。</p>';}
function moreInfoView(){return '<h1 class="section-title">更多资料</h1><p class="section-intro">9/25出发 · 10/6凌晨到家 · 所有航班为所在地当地时间</p><article class="info-card"><h2>航班与转机</h2>'+[
 ['9/25 · CX989','22:20 广州T3 → 23:40 香港','18:15从家中打车出发，目标19:15–19:45到机场。'],['9/26 · CX181','00:45 香港T1 → 11:45 悉尼','香港仅65分钟转机，机场内直达下一登机口。'],['10/1 · VA824','09:00 悉尼T2 → 10:35 墨尔本T3','06:15退房前往机场，机上无餐食。'],['10/5 · CX104','15:25 墨尔本T2 → 21:45 香港','目标12:15到机场，香港转机3小时30分钟。'],['10/6 · CX950','01:15 香港T1 → 02:20 广州','入境取行李后打车返家，预计04:20左右到家。']].map(f=>'<div class="flight"><strong>'+f[0]+'</strong>'+f[1]+'<br><span>'+f[2]+'</span></div>').join('')+'</article><article class="info-card"><h2>费用速查 / 4人</h2><div class="money"><div><small>人民币已确认</small><b>¥70,046.02</b><small>人均 ¥17,511.51</small></div><div><small>观鲸单独结算</small><b>A$604.94</b><small>澳元，不与人民币直接相加</small></div><div><small>餐饮预算估计</small><b>≈ A$2,760</b><small>人均 ≈ A$690，非已付款</small></div><div><small>酒店总住宿</small><b>9晚</b><small>悉尼5晚＋墨尔本4晚</small></div></div></article><a class="wide-link" href="#alternatives">查看备选景点 →</a><p class="note">照片版权归原作者或来源方，点击照片可查看来源。家庭详细地址及订单编号未包含在此公开页面。</p>';}
function profileView(){return segmented('我的旅行','行李清单、航班与费用资料集中查看。',[{id:'my-luggage',label:'行李清单',content:luggageView()},{id:'my-info',label:'出行资料',content:moreInfoView()}]);}
function infoView(){return '<h1 class="section-title">出行资料</h1><p class="section-intro">9/25出发 · 10/6凌晨到家 · 所有航班为所在地当地时间</p><article class="info-card"><h2>航班与转机</h2>'+[
 ['9/25 · CX989','22:20 广州T3 → 23:40 香港','18:15从家中打车出发，目标19:15–19:45到机场。'],['9/26 · CX181','00:45 香港T1 → 11:45 悉尼','香港仅65分钟转机，机场内直达下一登机口。'],['10/1 · VA824','09:00 悉尼T2 → 10:35 墨尔本T3','06:15退房前往机场，机上无餐食。'],['10/5 · CX104','15:25 墨尔本T2 → 21:45 香港','目标12:15到机场，香港转机3小时30分钟。'],['10/6 · CX950','01:15 香港T1 → 02:20 广州','入境取行李后打车返家，预计04:20左右到家。']].map(f=>'<div class="flight"><strong>'+f[0]+'</strong>'+f[1]+'<br><span>'+f[2]+'</span></div>').join('')+'</article><article class="info-card"><h2>费用速查 / 4人</h2><div class="money"><div><small>人民币已确认</small><b>¥70,046.02</b><small>人均 ¥17,511.51</small></div><div><small>观鲸单独结算</small><b>A$604.94</b><small>澳元，不与人民币直接相加</small></div><div><small>餐饮预算估计</small><b>≈ A$2,760</b><small>人均 ≈ A$690，非已付款</small></div><div><small>酒店总住宿</small><b>9晚</b><small>悉尼5晚＋墨尔本4晚</small></div></div></article><article class="info-card"><h2>用餐安排</h2><p><b>9/27午餐</b> Pancakes on the Rocks<br><b>9/27晚餐</b> Cafe Sydney / Opera Bar二选一，待订<br><b>9/28午餐</b> 新悉尼鱼市场海鲜<br><b>10/4午餐</b> 南墨尔本市场Dim Sims＋生蚝<br><b>10/1晚餐</b> Steer Dining Room和牛，South Yarra，待订<br><b>10/4晚餐</b> <span class="unplanned">【暂未安排】</span></p><p>其他未定餐食在时间线上以<span class="unplanned">【暂未安排】</span>标识。沃森湾Doyles为可选，Garfish仅随曼利备选路线考虑。</p></article><article class="info-card checklist"><h2>出发前待办</h2>'+tasks.map((t,i)=>'<label><input type="checkbox" data-check="'+i+'" '+(checked[i]?'checked':'')+'><span>'+esc(t)+'</span></label>').join('')+'<p id="save-note" class="note">勾选仅保存在当前设备浏览器。</p></article><p class="note">照片版权归原作者或来源方，点击照片可查看来源。照片仅作景点识别，实际现场状态可能不同。家庭详细地址及订单编号未包含在此公开页面。</p>';}
function render(){
 const hash=decodeURIComponent(location.hash.slice(1)),d=days.find(d=>d.id===hash);let view;
 if(['stay-food','food','hotels','shop-photo','profile','luggage','info','alternatives'].includes(hash)){view=hash==='food'?'food':hash==='hotels'||hash==='stay-food'?'hotels':hash==='alternatives'?'shop-photo':hash==='shop-photo'?'shop-photo':'profile';$('#main').innerHTML=hash==='food'?'<h1 class="section-title">美食安排</h1><p class="section-intro">按日期查看已安排与暂未安排的餐次。</p>'+foodContent():hash==='hotels'||hash==='stay-food'?'<h1 class="section-title">住宿安排</h1><p class="section-intro">酒店信息、房型照片与交通位置。</p>'+hotelsContent():hash==='shop-photo'?shopPhotoView():hash==='alternatives'?alternativesView():hash==='luggage'?luggageView():hash==='info'?moreInfoView():profileView();}
 else{view='trip';selected=d?.id||selected;$('#main').innerHTML=dayView(days.find(d=>d.id===selected));}
 $('#datebar').hidden=view!=='trip';document.querySelectorAll('[data-view]').forEach(a=>{a.toggleAttribute('aria-current',a.dataset.view===view);if(a.dataset.view===view)a.setAttribute('aria-current','page');});
 document.querySelectorAll('.date-chip').forEach(a=>{if(a.hash==='#'+selected)a.setAttribute('aria-current','date');else a.removeAttribute('aria-current');});
 document.querySelector('[data-view="trip"]').href='#'+selected;
 document.title=(view==='trip'?days.find(d=>d.id===selected).date+' '+days.find(d=>d.id===selected).title:({food:'美食安排',hotels:'住宿安排','shop-photo':'购物打卡',profile:'我的旅行'})[view])+'｜澳大利亚随行手册';
 window.scrollTo({top:0,behavior:'instant'});if(view==='trip'){const chip=document.querySelector('.date-chip[aria-current]'),rail=$('#dates');rail.scrollLeft=chip.offsetLeft-rail.offsetLeft-rail.clientWidth/2+chip.clientWidth/2;}
}
function directory(q=''){const term=q.trim().toLowerCase();const results=days.filter(d=>(JSON.stringify(d)+' '+[...d.rows,...d.optional].flatMap(r=>r.ids).map(id=>photos[id].cn+' '+photos[id].en).join(' ')).toLowerCase().includes(term));$('#directory-results').innerHTML=results.map(d=>'<a class="directory-item" href="#'+d.id+'"><small>'+esc(d.date)+' / '+esc(d.city)+'</small><b>'+esc(d.title)+'</b><p>'+d.rows.flatMap(r=>r.ids).map(id=>esc(photos[id].cn)).join(' · ')+'</p></a>').join('')+(results.length?'':'<p class="empty">没有找到匹配的行程，试试其他名称。</p>');}
$('#dates').innerHTML=days.map(d=>'<a class="date-chip" href="#'+d.id+'"><b>'+d.date.split(' ')[0]+'</b><span>'+d.date.split(' ')[1]+'</span></a>').join('');
$('#directory-button').onclick=()=>{lastFocus=document.activeElement;directory();$('#search').value='';$('#directory').showModal();};$('#search').addEventListener('input',e=>directory(e.target.value));
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)$('#'+close.dataset.close).close();const item=e.target.closest('.directory-item');if(item){$('#directory').close();if(location.hash===item.hash)render();}
 const segment=e.target.closest('[data-segment]');if(segment){const shell=segment.closest('.segment-shell');shell.querySelectorAll('[data-segment]').forEach(button=>button.setAttribute('aria-selected',String(button===segment)));shell.querySelectorAll('[data-segment-panel]').forEach(panel=>panel.hidden=panel.dataset.segmentPanel!==segment.dataset.segment);}
 const photo=e.target.closest('[data-photo]');if(photo){const p=photos[photo.dataset.photo];lastFocus=photo;$('#photo-title').textContent=p.cn;$('#photo-large').src=p.src;$('#photo-large').alt=p.cn;$('#photo-english').textContent=p.en;$('#photo-source').href=p.source;$('#photo-source').textContent='图片来源 · '+p.credit+' ↗';$('#photo-dialog').showModal();}});
document.addEventListener('change',e=>{if(e.target.matches('[data-check]')){checked[e.target.dataset.check]=e.target.checked;try{localStorage.setItem('au-mobile-checks-v2',JSON.stringify(checked));}catch{$('#save-note').textContent='当前浏览器无法保存，勾选仅本次有效。';}}});
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus();});});
window.addEventListener('hashchange',render);render();

