'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const {days,photos,alternatives}=TRIP;
Object.assign(photos,{
 'hotel-sydney-entrance':{cn:'悉尼小国民酒店',en:'Little National Hotel Sydney',source:'https://littlenationalhotel.com.au/sydney/',credit:'酒店官网',src:'assets/little-national-entrance.webp',width:625,height:1000},
 'hotel-sydney-room':{cn:'悉尼小国民酒店大床房',en:'Little National Room',source:'https://littlenationalhotel.com.au/sydney/rooms/ln-rooms/?lang=en',credit:'酒店官网',src:'assets/little-national-room.webp',width:1000,height:750},
 'hotel-melbourne-entrance':{cn:'墨尔本智选假日酒店正门',en:'Holiday Inn Express Melbourne Little Collins',source:'https://www.ihg.com/holidayinnexpress/hotels/us/en/melbourne/mellc/hoteldetail',credit:'IHG酒店官网',src:'assets/holiday-inn-entrance.webp',width:1000,height:929},
 'hotel-melbourne-room':{cn:'墨尔本智选假日大床房',en:'Standard Room',source:'https://www.ihg.com/holidayinnexpress/hotels/us/en/melbourne/mellc/hoteldetail',credit:'IHG酒店官网',src:'assets/holiday-inn-room.webp',width:1000,height:667},
 'mcdonalds-wynyard':{cn:"McDonald's Wynyard Station",en:'Wynyard Railway Concourse, Carrington St, Sydney',source:'https://commons.wikimedia.org/wiki/File:Mcdonalds_Australia.jpg',credit:'Hithere442 / Wikimedia Commons',src:'assets/mcdonalds.jpg',width:960,height:720}
});
const map=(a,b,mode)=>'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(a)+'&destination='+encodeURIComponent(b)+'&travelmode='+mode;
const searchMap=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);
const link=(href,label)=>'<a class="map-button" target="_blank" rel="noopener" href="'+esc(href)+'">'+esc(label)+' ↗</a>';
let selected='day-1',lastFocus=null;
const tasks=['确认国际航班、65分钟香港转机及行李直挂','提前购买便利店早餐，早出日晚上备好','9/27观鲸：07:40前到Campbell’s Cove Pontoon','9/29用NextThere核对08:13、11:00、15:01、16:55班次，并确认The Hill Bar营业','9/30复核08:17、10:15、11:50、14:02、15:16、16:40公交与渡轮','确认10/2及10/3集合点、火车票时刻和实际停靠景点','落实海景晚餐与Steer Dining Room订位','10/4按当地夏令时；10/5目标12:15抵达机场'];
const luggageGroups=[
 ['证件与支付',['护照（与签证绑定护照一致）','澳大利亚签证批准信／电子版离线存档','身份证','证件电子版：手机离线＋云端备份','银行卡／信用卡＋少量澳元现金','机票、酒店、火车与活动订单截图','旅行保险保单＋紧急联系电话','黑色签字笔（填写入境旅客卡）','按需｜驾照＋认可翻译件（本次不自驾可不带）']],
 ['衣物与穿搭',['日常衣服','拍照穿搭','防风防水外套＋可叠穿薄毛衣','防晒衣','泳衣','内衣／胸贴','睡衣','一次性内裤＋袜子','舒适防滑运动鞋','拖鞋','遮阳帽＋墨镜','丝巾／围巾／帽子','饰品、首饰、手表与腰带']],
 ['洗漱用品 · 小样',['牙刷、牙膏与牙线','洗发水、护发素与护发精油','沐浴露与身体乳','止汗露与剃须刀','一次性马桶垫','按需｜一次性四件套','一次性毛巾／浴巾','干发帽','一次性洗脸巾','按需｜折叠衣架','按需｜花洒喷头','搓澡巾']],
 ['护肤修护',['卸妆产品＋化妆棉','洗面奶','爽肤水','乳液','精华','面霜','眼霜','面部高倍防晒','身体防晒','补水面膜／眼膜','痘痘贴','润唇膏','护手霜','修眉刀']],
 ['彩妆与工具',['化妆包','底妆＋遮瑕','眉笔＋眼影＋眼线＋睫毛膏','腮红＋口红＋定妆产品','化妆刷／粉扑＋睫毛夹','按需｜隐形眼镜、护理液与备用眼镜']],
 ['电子数码',['手机','耳机','Pocket 3＋存储卡＋保护盒','各种充电器与数据线','充电宝：≤100Wh、最多2个、仅随身携带','澳标Type I转换插头','小型排插','自拍杆／三脚支架','电话卡／eSIM＋取卡针','按需｜电脑及充电器','行李牌＋AirTag／定位器']],
 ['常备药品',['肠胃药','感冒药＋退烧药','痛经／止痛药','晕车／晕船药','过敏药','创可贴＋消毒棉片／碘伏棉棒','驱蚊液＋止痒膏','口腔溃疡贴','个人专属常备药','处方药原包装＋处方／英文医生说明','电子体温计']],
 ['卫生与收纳',['耳塞＋眼罩','干湿分离收纳袋','护肤品分装瓶','卫生巾／护垫','镜子＋梳子','折叠雨伞','U型枕','家钥匙','酒精湿巾','便携纸巾','口罩＋发圈＋发夹','密封袋／备用塑料袋','脏衣袋','折叠购物袋','保温杯／水杯','行李秤','长途飞行压缩袜']],
 ['入境、航空与退税',['入境前清理肉蛋奶、水果、种子等食品；不确定就申报','液体单瓶≤100ml，放透明袋随身过安检','充电宝不托运；国泰航班不放头顶行李架、不在机上使用','重要证件、药品、相机与贵重物品放随身行李','TRS商品、吊牌与同店满A$300发票','TRS商品随身携带／穿着，提前填写TRS App']]
];
let checked={};try{checked=JSON.parse(localStorage.getItem('au-mobile-checks-v2')||'{}');}catch{}
const icon=(name,cls='')=>{const paths={pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',train:'<rect x="5" y="3" width="14" height="16" rx="3"/><path d="M8 21l2-2M16 19l2 2M8 8h8M8 14h.01M16 14h.01"/>',walk:'<circle cx="13" cy="4" r="2"/><path d="m10 22 1-7-3-3 2-5 4 3 3 1M15 22l-2-6 4-2"/>',car:'<path d="m5 17-2-2 2-6h14l2 6-2 2H5Z"/><path d="m7 9 2-4h6l2 4M6 17v3M18 17v3M7 14h.01M17 14h.01"/>',plane:'<path d="M22 2 9 15M22 2l-6 20-4-9-9-4 19-7Z"/>',fork:'<path d="M4 13h16M6 13a6 6 0 0 1 12 0M12 7V4M3 17h18"/>',shop:'<path d="M4 7h16l-1 14H5L4 7Z"/><path d="M8 9V5a4 4 0 0 1 8 0v4"/>',building:'<path d="M4 22V4l8-2 8 2v18M9 8h.01M15 8h.01M9 12h.01M15 12h.01M9 16h.01M15 16h.01M10 22v-3h4v3"/>',chevron:'<path d="m9 18 6-6-6-6"/>',zoom:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'};return '<svg class="'+cls+'" viewBox="0 0 24 24" aria-hidden="true">'+(paths[name]||paths.pin)+'</svg>';};
function timeMeta(value){const matches=String(value).match(/\d{1,2}:\d{2}/g)||[];if(!matches.length)return {primary:String(value).split(/[–—]/)[0],period:'',until:''};const hour=Number(matches[0].split(':')[0]),period=hour<6?'凌晨':hour<12?'上午':hour<14?'中午':hour<18?'下午':'晚上';return {primary:matches[0],period,until:matches[1]?'至 '+matches[1]:''};}
function placeType(r){const text=(r.title+' '+r.note).toLowerCase();if(/机场|airport|cx\d|va\d|航班|登机|安检|候机/.test(text))return ['景点','plane'];if(/购物|手信|minimeeq|mini meeq|paddy|arc.?teryx|westfield|pitt street|qvb/.test(text))return ['景点','shop'];if(/酒店|入住|退房|行李/.test(text))return ['住宿','building'];return ['景点','pin'];}
function travelIcon(mode){return mode==='walking'?'walk':mode==='driving'?'car':mode==='transit'?'train':'train';}
function railTime(r){const t=timeMeta(r.time);return '<div class="time-block"><time class="time">'+esc(t.primary)+'</time><span>'+esc(t.period)+'</span>'+(t.until?'<small>'+esc(t.until)+'</small>':'')+'</div>';}
function imageCard(id,extra='') {const p=photos[id];if(!p)return '';return '<div class="event-card"><button class="photo-button" data-photo="'+id+'" aria-label="放大'+esc(p.cn)+'"><img src="'+p.src+'" alt="'+esc(p.cn)+'" width="'+p.width+'" height="'+p.height+'" loading="lazy" decoding="async"><span>查看大图</span></button><div class="event-copy"><h3>'+esc(p.cn)+'</h3><span class="english">'+esc(p.en)+'</span>'+extra+'</div></div>';}
function event(r){
 const time=railTime(r);
 if(r.kind==='move')return '<article class="event move">'+time+'<details class="route-strip"><summary><span class="route-symbol">'+icon(travelIcon(r.mode))+'</span><span class="route-main"><span class="type-badge">交通</span><b>'+esc(r.title)+'</b>'+(r.origin&&r.dest?'<small>'+esc(r.origin)+' → '+esc(r.dest)+'</small>':'')+'</span><span class="route-chevron">'+icon('chevron')+'</span></summary><div class="route-detail"><p>'+esc(r.note)+'</p>'+(r.origin?link(map(r.origin,r.dest,r.mode),r.mode==='transit'?'查看公共交通':r.mode==='walking'?'打开步行导航':'查看行车路线'):'<span class="note">使用叫车软件填写实际地址</span>')+'</div></details></article>';
 if(r.kind==='meal'){const mealText=(r.food||'')+' '+r.note,mealPhoto=/mcdonald/i.test(mealText)?'mcdonalds-wynyard':/便利店早餐/.test(mealText)?'coles':/鱼市场|龙虾|生蚝|海鲜/.test(mealText)?'fish':/南墨尔本市场|dim sim/i.test(mealText)?'market':'';return '<article class="event meal">'+time+'<div class="event-card meal-card">'+(mealPhoto?'<button class="photo-button" data-photo="'+mealPhoto+'" aria-label="查看用餐地点照片"><img src="'+photos[mealPhoto].src+'" alt="'+esc(photos[mealPhoto].cn)+'" loading="lazy"></button>':'<div class="meal-visual">'+icon('fork')+'</div>')+'<div class="event-copy"><div class="card-top"><span class="type-badge">美食</span>'+(r.mapUrl?'<a class="nav-pill" target="_blank" rel="noopener" href="'+esc(r.mapUrl)+'">'+icon('plane')+'导航</a>':'')+'</div><h3>'+esc(r.title)+'</h3><span class="english '+(r.food?'':'unplanned')+'">'+esc(r.food||'【暂未安排】')+'</span>'+(r.note?'<p>'+esc(r.note)+'</p>':'')+'</div></div></article>';}
 const [type,typeIcon]=placeType(r),id=r.ids[0],p=id?photos[id]:null,title=p?p.cn:r.title,english=p?p.en:'',note=p?r.note:r.note;
 return '<article class="event stop">'+time+'<div class="event-card place-card">'+(p?'<button class="photo-button" data-photo="'+id+'" aria-label="放大'+esc(p.cn)+'"><img src="'+p.src+'" alt="'+esc(p.cn)+'" width="'+p.width+'" height="'+p.height+'" loading="lazy" decoding="async"><span>'+icon('zoom')+'</span></button>':'<div class="place-visual">'+icon(typeIcon)+'</div>')+'<div class="event-copy"><div class="card-top"><span class="type-badge">'+type+'</span>'+(p?'<a class="nav-pill" target="_blank" rel="noopener" href="'+esc(searchMap(p.en))+'">'+icon('plane')+'导航</a>':'')+'</div><h3>'+esc(title)+'</h3>'+(english?'<span class="english">'+esc(english)+'</span>':'')+(note?'<p>'+esc(note)+'</p>':'')+'</div></div></article>';
}
function dayView(d){
 const idx=days.indexOf(d);
 return '<div class="day-layout"><section class="day-schedule" aria-label="当天时间线"><div class="track-head"><div><span class="track-kicker">TODAY</span><h2>今日行程</h2></div><p>景点 · 交通 · 美食</p></div><div class="timeline">'+d.rows.map(event).join('')+'</div>'+(d.optional.length?'<details class="optional"><summary>可选支线／团方候选</summary><div class="timeline">'+d.optional.map(event).join('')+'</div></details>':'')+'<div class="day-pager">'+(idx?'<a href="#'+days[idx-1].id+'">← '+days[idx-1].date.split(' ')[0]+'</a>':'')+(idx<days.length-1?'<a href="#'+days[idx+1].id+'">'+days[idx+1].date.split(' ')[0]+' →</a>':'<a href="#profile">返程资料 →</a>')+'</div></section></div>';
}
function hotelsContent(){const hotels=[
 {city:'SYDNEY / 悉尼',name:'悉尼小国民酒店',en:'Little National Hotel Sydney',room:'hotel-sydney-room',door:'hotel-sydney-entrance',checkin:'9月26日',checkout:'10月1日',nights:'5晚',address:'26 Clarence St, Sydney',query:'Little National Hotel Sydney 26 Clarence Street'},
 {city:'MELBOURNE / 墨尔本',name:'小柯林斯街智选假日',en:'Holiday Inn Express Little Collins',room:'hotel-melbourne-room',door:'hotel-melbourne-entrance',checkin:'10月1日',checkout:'10月5日',nights:'4晚',address:'589–599 Little Collins St, Melbourne',query:'Holiday Inn Express Melbourne Little Collins'}
];return '<div class="hotel-showcase">'+hotels.map(h=>'<article class="hotel-feature"><div class="hotel-gallery" aria-label="'+esc(h.name)+'照片，左右滑动查看"><button class="hotel-slide" data-photo="'+h.room+'" aria-label="放大房间照片"><img src="'+photos[h.room].src+'" alt="'+esc(photos[h.room].cn)+'"><span>房间 · 1/2</span></button><button class="hotel-slide" data-photo="'+h.door+'" aria-label="放大酒店正门照片"><img src="'+photos[h.door].src+'" alt="'+esc(photos[h.door].cn)+'"><span>正门 · 2/2</span></button></div><div class="hotel-feature-body"><div class="hotel-title-row"><div><small>'+h.city+'</small><h2>'+esc(h.name)+'</h2><p>'+esc(h.en)+'</p></div><a class="nav-pill" target="_blank" rel="noopener" href="'+esc(searchMap(h.query))+'">'+icon('plane')+'导航</a></div><div class="stay-facts"><div><small>入住</small><b>'+h.checkin+'</b></div><div><small>退房</small><b>'+h.checkout+'</b></div><div><small>晚数</small><b>'+h.nights+'</b></div></div><p class="hotel-address">⌖ '+esc(h.address)+'</p></div></article>').join('')+'</div>';}
function foodContent(){const meals=days.flatMap(d=>d.rows.filter(r=>r.kind==='meal').map(r=>({day:d,time:r.time,title:r.title,food:r.food,note:r.note}))),planned=meals.filter(m=>m.food&&m.food!=='便利店早餐'),breakfast={day:days[2],time:'9/27–10/5 · 共9次',title:'早餐',food:'Coles便利店早餐',note:'前一晚按次日出发时间准备'};const photoFor=m=>/mcdonald/i.test(m.food||'')?'mcdonalds-wynyard':/便利店早餐/.test(m.food||'')?'coles':/鱼市场|龙虾|生蚝|海鲜/.test((m.food||'')+' '+(m.note||''))?'fish':/南墨尔本市场|dim sim/i.test((m.food||'')+' '+(m.note||''))?'market':'';const card=m=>{const photo=photoFor(m);return '<a class="food-card" href="#'+m.day.id+'">'+(photo?'<img src="'+photos[photo].src+'" alt="'+esc(photos[photo].cn)+'" loading="lazy">':'<span class="food-placeholder">'+icon('fork')+'</span>')+'<div><small>'+esc(m.day.date)+' · '+esc(m.time)+'</small><h2>'+esc(m.food)+'</h2><p>'+esc(m.title)+(m.note?' · '+esc(m.note):'')+'</p><span class="food-tag">'+(m.title==='早餐'?'早餐':m.title==='午餐'?'午餐':'晚餐')+'</span></div></a>';};return '<div class="food-grid">'+[breakfast,...planned].map(card).join('')+'</div>';}
function moduleHeader(title,intro){return '<a class="module-page-head" href="#'+selected+'" aria-label="返回行程"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6"/></svg><span><b>'+esc(title)+'</b><small>'+esc(intro)+'</small></span></a>';}
function segmented(title,intro,tabs){return moduleHeader(title,intro)+'<div class="segment-shell"><div class="segmented" role="tablist">'+tabs.map((t,i)=>'<button role="tab" data-segment="'+t.id+'" aria-selected="'+(i?'false':'true')+'">'+t.label+'</button>').join('')+'</div>'+tabs.map((t,i)=>'<section class="segment-panel" data-segment-panel="'+t.id+'" '+(i?'hidden':'')+'>'+t.content+'</section>').join('')+'</div>';}
function stayFoodView(){return segmented('吃住安排','酒店信息与每日用餐集中查看；点击餐次可回到当天时间线。',[{id:'hotels',label:'酒店',content:hotelsContent()},{id:'food',label:'美食',content:foodContent()}]);}
function alternativesView(){return '<h1 class="section-title">备选景点</h1><p class="section-intro">这些景点已移出主行程，照片保留在这里。临时替换时需重新核对交通与时间。</p><div class="alternatives-grid">'+alternatives.map(id=>imageCard(id,'<p>'+link(searchMap(photos[id].en+(id==='arcade'?' Melbourne':' Sydney')),'查看位置')+'</p>')).join('')+'</div>';}
function shoppingContent(){return '<div class="shop-grid"><article class="info-card"><small>9/28 · 15:30–16:00</small><h2>Mini MeeQ Sydney</h2><p>Westfield Sydney Shop 1027，重点找澳洲限定版Hello Kitty；从QVB步行约4分钟。</p>'+link(searchMap('Mini MeeQ Sydney'),'门店导航')+'</article><article class="info-card"><small>9/30 · 17:35–18:00</small><h2>Paddy’s Markets · 手信</h2><p>Haymarket／Market City内，周三18:00关门。按清单定向购买；渡轮晚点时缩短或取消。</p>'+link(searchMap("Paddy's Markets Haymarket"),'市场导航')+'</article><article class="info-card"><small>9/30 · 10:45–11:45</small><h2>Arc’teryx · Westfield Bondi Junction</h2><p>安排在Coogee与Bondi Beach之间，购物1小时。同行人可在商场休息。</p>'+link(searchMap("Arc\'teryx Westfield Bondi Junction"),'商场导航')+'<p class="note">同一商店单张发票尽量满A$300，保留商品、吊牌和发票。</p></article><article class="info-card"><small>Plan B · 9/28 15:55–17:30</small><h2>Arc’teryx · The Galeries</h2><p>500 George St，距悉尼酒店步行约5–8分钟；仅在9/30需要释放时间时启用。</p>'+link(searchMap("Arc\'teryx The Galeries Sydney"),'门店导航')+'</article><article class="info-card"><h2>TRS退税</h2><p>10/5只在墨尔本机场T2国际出发办理。商品随身携带或穿着，勿托运；提前填写TRS App并备好发票。</p></article></div>';}
function photoContent(){const groups=days.map(d=>({d,ids:[...new Set(d.rows.flatMap(r=>r.ids))]})).filter(g=>g.ids.length);return '<div class="photo-index">'+groups.map(g=>'<section class="photo-day"><a href="#'+g.d.id+'"><small>'+esc(g.d.date)+'</small><b>'+esc(g.d.title)+'</b></a><div>'+g.ids.map(id=>imageCard(id)).join('')+'</div></section>').join('')+'</div><a class="wide-link" href="#alternatives">查看备选景点与照片 →</a>';}
function shopPhotoView(){return segmented('购物打卡','用镜头收藏旅途中的美好',[{id:'shopping',label:'购物',content:shoppingContent()},{id:'photos',label:'拍照',content:photoContent()}]);}
function luggageView(){let index=0,total=luggageGroups.reduce((sum,g)=>sum+g[1].length,0);const groups=luggageGroups.map(g=>'<section class="luggage-group"><h2>'+esc(g[0])+'<small>'+g[1].length+'项</small></h2>'+g[1].map(item=>{const key='luggage-'+index++;return '<label><input type="checkbox" data-check="'+key+'" '+(checked[key]?'checked':'')+'><span>'+esc(item)+'</span></label>';}).join('')+'</section>').join('');return '<p class="tab-intro">共'+total+'项 · 勾选状态仅保存在当前手机</p><div class="luggage-grid">'+groups+'</div><article class="info-card"><h2>充电宝提醒</h2><p>每人最多携带2个，仅限随身行李；不得放头顶行李架，也不能在机上使用或充电。</p><p>'+link('https://www.cathaypacific.com/cx/zh_CN/baggage/controlled-and-banned-items/lithium-batteries.html','国泰电池规则')+'</p></article><p id="save-note" class="note">换手机或清除浏览器数据后，需要重新勾选。</p>';}
function flightView(){const flights=[
 ['CX989','9月25日 · 国泰航空','22:20','广州','Guangzhou (CAN)','23:40','香港','Hong Kong (HKG)','约1h20m','出发 T3 / 到达 T1','18:15从家中打车出发'],
 ['CX181','9月26日 · 国泰航空','00:45','香港','Hong Kong (HKG)','11:45','悉尼','Sydney (SYD)','约9h','出发 T1 / 到达 T1','转机65分钟，行李直挂'],
 ['VA824','10月1日 · 维珍澳洲','09:00','悉尼','Sydney (SYD)','10:35','墨尔本','Melbourne (MEL)','约1h35m','出发 T2 / 到达 T3','06:15从酒店出发'],
 ['CX104','10月5日 · 国泰航空','15:25','墨尔本','Melbourne (MEL)','21:45','香港','Hong Kong (HKG)','约9h20m','出发 T2 / 到达 T1','目标12:15抵达机场'],
 ['CX950','10月6日 · 国泰航空','01:15','香港','Hong Kong (HKG)','02:20','广州','Guangzhou (CAN)','约1h05m','出发 T1 / 广州航站楼待确认','入境取行李后打车回家']
];return '<div class="flight-list">'+flights.map(f=>'<article class="flight-card"><div class="flight-head"><b>'+f[0]+'</b><span>'+f[1]+'</span></div><div class="flight-route"><div><strong>'+f[2]+'</strong><b>'+f[3]+'</b><small>'+f[4]+'</small></div><div class="flight-plane">'+icon('plane')+'<small>'+f[8]+'</small></div><div><strong>'+f[5]+'</strong><b>'+f[6]+'</b><small>'+f[7]+'</small></div></div><p>'+f[9]+'</p><em>'+f[10]+'</em></article>').join('')+'</div>';}
function practicalView(){const items=[['时差','悉尼比北京时间快2小时；10月起墨尔本进入夏令时，比北京时间快3小时。'],['插头','澳洲使用I型三脚扁插，电压230V，必须携带转换插头。'],['悉尼交通','可用Visa／Mastercard等非接触式银行卡或手机支付；全程必须用同一张卡或同一设备Tap on／Tap off。'],['墨尔本交通','优先准备实体Myki；银行卡感应支付是否覆盖所乘线路，以现场读卡器标识为准。'],['支付','刷卡为主，准备A$100–200现金；一人一张交通付款卡，避免多人共用造成计费错误。'],['网络','电话卡或eSIM提前开通；离线保存酒店地址、机票、护照和Google地图重点区域。'],['饮水与小费','自来水通常可直接饮用；餐厅小费不强制，账单没有服务费时可自行决定。'],['入境申报','食品、药品、植物、动物制品及接触过泥土的鞋具不确定时一律申报，申报不等于禁止携带。'],['个人药品','保留原包装和英文成分说明；通常按个人使用量准备，不超过约3个月用量。'],['紧急求助','警察／消防／救护统一拨000；中国驻悉尼总领馆 +61 2 9550 5519。'],['TRS退税','同一ABN商户累计满A$300、离境前60天内购买；随身携带商品、护照和税务发票到机场办理。']];return '<article class="utility-card">'+items.map(t=>'<p><span>ⓘ</span><b>'+t[0]+'</b><em>'+esc(t[1])+'</em></p>').join('')+'</article><div class="reference-links">'+link('https://transportnsw.info/tickets-fares/contactless-payments','悉尼交通支付')+link('https://www.ptv.vic.gov.au/tickets/myki/travel-with-myki/','墨尔本Myki')+link('https://www.agriculture.gov.au/travelling/bringing-mailing-goods','澳洲入境申报')+'</div><article class="info-card"><h2>费用速查 / 4人</h2><div class="money"><div><small>人民币已确认</small><b>¥70,046.02</b></div><div><small>观鲸单独结算</small><b>A$604.94</b></div><div><small>餐饮预算估计</small><b>≈ A$2,760</b></div><div><small>酒店住宿</small><b>9晚</b></div></div></article>';}
function phrasesView(){const groups=[['问路与交通',[['请问这个怎么走？','How do I get to this place?'],['这是去悉尼市中心的车吗？','Does this go to Sydney city centre?'],['我应该在哪一站下车？','Which stop should I get off at?'],['这个站台对吗？','Is this the right platform?'],['请告诉我到了哪一站。','Please let me know when we get there.']]],['酒店',[['我想办理入住。','I would like to check in.'],['可以先寄存行李吗？','Could you store our luggage, please?'],['早餐不需要，谢谢。','We do not need breakfast, thank you.'],['可以延迟退房吗？','Could we have a late check-out?'],['房间里没有热水。','There is no hot water in the room.']]],['餐厅',[['麻烦买单，谢谢。','Could I have the bill, please?'],['有中文菜单吗？','Do you have a Chinese menu?'],['我不吃辣。','No chilli for me, please.'],['我对海鲜过敏。',"I'm allergic to seafood."],['可以打包吗？','Could I get this to take away?'],['请给我一杯水。','Could I have a glass of water, please?']]],['购物与求助',[['这个可以退税吗？','Is this eligible for a tax refund?'],['请给我税务发票。','Could I have a tax invoice, please?'],['有其他尺码吗？','Do you have this in another size?'],['可以刷卡吗？','Can I pay by card?'],['请帮我拍张照片可以吗？','Could you take a photo for me, please?'],['请问洗手间在哪里？','Where is the restroom?'],['请帮帮我，我迷路了。',"Could you help me? I'm lost."],['请帮我报警／叫救护车。','Please call the police / an ambulance.']]]];return '<div class="phrase-groups">'+groups.map(g=>'<section><h2>'+g[0]+'</h2><article class="phrases-card">'+g[1].map(p=>'<div><b>'+p[0]+'</b><span>'+p[1]+'</span></div>').join('')+'</article></section>').join('')+'</div>';}
function moreInfoView(){return flightView();}
function profileView(){return '<div class="profile-tabs">'+segmented('我的','行李、航班与旅途中随时要用的资料',[{id:'my-luggage',label:'行李清单',content:luggageView()},{id:'my-flights',label:'航班信息',content:flightView()},{id:'my-practical',label:'实用信息',content:practicalView()},{id:'my-phrases',label:'常用短句',content:phrasesView()}])+'</div>';}
function infoView(){return '<h1 class="section-title">出行资料</h1><p class="section-intro">9/25出发 · 10/6凌晨到家 · 所有航班为所在地当地时间</p><article class="info-card"><h2>航班与转机</h2>'+[
 ['9/25 · CX989','22:20 广州T3 → 23:40 香港','18:15从家中打车出发，目标19:15–19:45到机场。'],['9/26 · CX181','00:45 香港T1 → 11:45 悉尼','香港仅65分钟转机，机场内直达下一登机口。'],['10/1 · VA824','09:00 悉尼T2 → 10:35 墨尔本T3','06:15退房前往机场，机上无餐食。'],['10/5 · CX104','15:25 墨尔本T2 → 21:45 香港','目标12:15到机场，香港转机3小时30分钟。'],['10/6 · CX950','01:15 香港T1 → 02:20 广州','入境取行李后打车返家，预计04:20左右到家。']].map(f=>'<div class="flight"><strong>'+f[0]+'</strong>'+f[1]+'<br><span>'+f[2]+'</span></div>').join('')+'</article><article class="info-card"><h2>费用速查 / 4人</h2><div class="money"><div><small>人民币已确认</small><b>¥70,046.02</b><small>人均 ¥17,511.51</small></div><div><small>观鲸单独结算</small><b>A$604.94</b><small>澳元，不与人民币直接相加</small></div><div><small>餐饮预算估计</small><b>≈ A$2,760</b><small>人均 ≈ A$690，非已付款</small></div><div><small>酒店总住宿</small><b>9晚</b><small>悉尼5晚＋墨尔本4晚</small></div></div></article><article class="info-card"><h2>用餐安排</h2><p><b>9/27午餐</b> Pancakes on the Rocks<br><b>9/27晚餐</b> Cafe Sydney / Opera Bar二选一，待订<br><b>9/28午餐</b> 新悉尼鱼市场海鲜<br><b>10/4午餐</b> 南墨尔本市场Dim Sims＋生蚝<br><b>10/1晚餐</b> Steer Dining Room和牛，South Yarra，待订<br><b>10/4晚餐</b> <span class="unplanned">【暂未安排】</span></p><p>其他未定餐食在时间线上以<span class="unplanned">【暂未安排】</span>标识。沃森湾Doyles为可选，Garfish仅随曼利备选路线考虑。</p></article><article class="info-card checklist"><h2>出发前待办</h2>'+tasks.map((t,i)=>'<label><input type="checkbox" data-check="'+i+'" '+(checked[i]?'checked':'')+'><span>'+esc(t)+'</span></label>').join('')+'<p id="save-note" class="note">勾选仅保存在当前设备浏览器。</p></article><p class="note">照片版权归原作者或来源方，点击照片可查看来源。照片仅作景点识别，实际现场状态可能不同。家庭详细地址及订单编号未包含在此公开页面。</p>';}
function renderHeader(view,d){const header=$('#page-header'),isTrip=view==='trip'&&Boolean(d);header.parentElement.hidden=!isTrip;header.classList.toggle('has-cover',isTrip);if(!isTrip){header.innerHTML='';return;}const idx=days.indexOf(d);header.innerHTML='<img src="'+photos[d.cover].src+'" alt="'+esc(photos[d.cover].cn)+'"><div><span>'+esc(d.date)+' · '+esc(d.city)+'</span><h1>'+esc(d.title)+'</h1><p>2026 · '+(idx===0?'出发日':idx===10?'返程日':'第 '+idx+' 天')+'</p></div>';}
function render(){
 const hash=decodeURIComponent(location.hash.slice(1)),d=days.find(d=>d.id===hash);let view;
 if(['stay-food','food','hotels','shop-photo','profile','luggage','info','alternatives'].includes(hash)){view=hash==='food'?'food':hash==='hotels'||hash==='stay-food'?'hotels':hash==='alternatives'?'shop-photo':hash==='shop-photo'?'shop-photo':'profile';$('#main').innerHTML=hash==='food'?moduleHeader('美食','查看旅途中已安排的餐次')+foodContent():hash==='hotels'||hash==='stay-food'?moduleHeader('住宿','酒店房型、入住日期与位置')+hotelsContent():hash==='shop-photo'?shopPhotoView():hash==='alternatives'?alternativesView():hash==='luggage'?luggageView():hash==='info'?moreInfoView():profileView();}
 else{view='trip';selected=d?.id||selected;$('#main').innerHTML=dayView(days.find(d=>d.id===selected));}
 renderHeader(view,view==='trip'?days.find(d=>d.id===selected):null);
 $('#datebar').hidden=view!=='trip';document.querySelectorAll('[data-view]').forEach(a=>{a.toggleAttribute('aria-current',a.dataset.view===view);if(a.dataset.view===view)a.setAttribute('aria-current','page');});
 document.querySelectorAll('.date-chip').forEach(a=>{if(a.hash==='#'+selected)a.setAttribute('aria-current','date');else a.removeAttribute('aria-current');});
 document.querySelector('[data-view="trip"]').href='#'+selected;
 document.title=(view==='trip'?days.find(d=>d.id===selected).date+' '+days.find(d=>d.id===selected).title:({food:'美食安排',hotels:'住宿安排','shop-photo':'购物打卡',profile:'我的旅行'})[view])+'｜澳大利亚随行手册';
 window.scrollTo({top:0,behavior:'instant'});if(view==='trip'){const chip=document.querySelector('.date-chip[aria-current]'),rail=$('#dates');rail.scrollLeft=Math.max(0,chip.offsetLeft-rail.offsetLeft-14);}
}
$('#dates').innerHTML=days.map(d=>'<a class="date-chip" href="#'+d.id+'"><b>'+d.date.split(' ')[0]+'</b><span>'+d.date.split(' ')[1]+'</span></a>').join('');
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)$('#'+close.dataset.close).close();
 const segment=e.target.closest('[data-segment]');if(segment){const shell=segment.closest('.segment-shell');shell.querySelectorAll('[data-segment]').forEach(button=>button.setAttribute('aria-selected',String(button===segment)));shell.querySelectorAll('[data-segment-panel]').forEach(panel=>panel.hidden=panel.dataset.segmentPanel!==segment.dataset.segment);}
 const photo=e.target.closest('[data-photo]');if(photo){const p=photos[photo.dataset.photo];lastFocus=photo;$('#photo-title').textContent=p.cn;$('#photo-large').src=p.src;$('#photo-large').alt=p.cn;$('#photo-english').textContent=p.en;$('#photo-source').href=p.source;$('#photo-source').textContent='图片来源 · '+p.credit+' ↗';$('#photo-dialog').showModal();}});
document.addEventListener('change',e=>{if(e.target.matches('[data-check]')){checked[e.target.dataset.check]=e.target.checked;try{localStorage.setItem('au-mobile-checks-v2',JSON.stringify(checked));}catch{$('#save-note').textContent='当前浏览器无法保存，勾选仅本次有效。';}}});
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus();});});
window.addEventListener('hashchange',render);render();


